name: preview
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.0
      with:
        branch: gh-pages
        folder: dist
      env:
        ACCESS_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        BUILD_SCRIPT: npm install && npm run build
