name: preview
on:
  push
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@main

    - name: buildAndDeploy
      uses: c2hy/caviar-webui-action@main
      env:
        ACCESS_TOKEN: ${{ secrets.deploy_token }}
        BRANCH: gh-pages
        FOLDER: dist
        BUILD_SCRIPT: npm install && npm run build
