name: preview
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Install and Build
        run: |
          npm install
          npm run build
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.0
      env:
        ACCESS_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist
